
---
apiVersion: v1
kind: Config
current-context: garden-kyma--eea8f6e-external
clusters:
- name: garden-kyma--eea8f6e-external
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRQmxLcXYva0hEU00xZDJUOGFYSVljREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TlRBek1UWXlNalF5TURWYUZ3MHpOVEF6TVRZeU1qUXpNRFZhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUExWkcyCkthSFNCOVJDNkY3NXVNUUxtVlR6c1ZxdHM2Zk02QjVLTHVoUGtLRlZoWXpVM29NY255Zy8zQkg1c2dNNGxNcysKVDlGeFJjU0lnMEV6Y3JYbWpVaktGTFpMQjY3ZFovWDdZb0xIcE1URy9uNWdORFl3am94UjhZZG9xNDVyK25RYgp1bEJub05pT29KQ3RnZ3g5ZkpGTStxVWxoOVFsbk1lelhrak1xdU5STXN4b1c0OHpIUnYvVXYvRUswRS95NS9XCmZiMjBZNDVFRUt3c2JtMEVkSURTSVdweFpYTGZZWkVaamkyc2ZMdDlwSUFqMkdRdy9iU1ZrbDBYS0Z5dXg3bnUKS1d2dER2dHRuSDNLN1FJbGtSWGxsd0oxZzE3MHY2cmthKzNPdHVneHR1Y0dJejFNSDBPckRudVNWN3g1NnI3dQpBUEp1WEVmbmJVVDdiamlOTHVydUxCb0g1NVVqeHlYYWdhcmg5dzFZRWpLanRoVFJldzd4bmdpcVRhNkhBRUNICndRd1UvaGJEU1RMWE1aTUJaUzBiWGZoZ3VxTTR0eUFzREtoTlhPNTcyZjdRMWlpMHhjWVpPNndyT2Q5YkFUTzUKem90QWxSNUx1QWIrU0hndFd5NnkzTzF6ZTZtbWFxdHBxQjU1N2xlNjhQYUx6V2hxaTEzc3AxU0t5OTcxQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUW4wdDlzaSsyNUhwcmVVTFM4bWhDNUg4N2Y4REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBdTh0aFlhK2UKQjAzcTBFaG8zRktOQ3ZhVEFOYS83LzErMUFud1JQTWZKbHpaVnpoMEdXTEpWazFRUW5uSE0zSGhUMjdWV21DTApCbnFIanZUZGZtbWRzTFk3ZUV0Q1VIWFFZSGlwYkpyZFR1RSttL1hxN3NJSHFpMGQyRW8zbHVaMXpPZjlTdWJBCnVLcXpTNjgzNFUvYm9qam5oSUNOYUYxT1BqVCtaeHM2RjlsMVJHaW5NNGlVV0g1elZPTzRWN21sUmlOZWNwU2MKNE9EVmVlMFJ6Vmd5YkQyWld2aGY5byttSmVPbU9LMTVqdlpxK3ZIR1VEWGVpdmVkQkxESFl1RWlkdWJrZFFURAp2UGdXQmY2NU5zbFNhLzZRRFIzamdHZjRyUHpMdTgxeC9UWVI2eVlBS0RyYmE5WTdlazM2NlNTejFtOHZBZmlRClIrWUNHV1BHU1FqZk1NM0plTDFtNEdqL0dvamhJb01aRURaNHhiUldNQlZrUHBXTW1HdWdkSVQ5bUxTQzBoR3oKT3JmME9PKzJzWEU3WDhLdUc4Mmx2Z3BUYXF0cFA5Rmw3SStrTlZZbWg3cFQ1Sk4xVUJlc0ZKZFgxcjZDMTZxVAprMTZjQWxsVnBnNEpOczk2ZnZpVStLTEVJSGxMeGEzS2VnUWxiN3dzbXZNVURodWFYR0JLaWJTZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.eea8f6e.kyma.ondemand.com
contexts:
- name: garden-kyma--eea8f6e-external
  context:
    cluster: garden-kyma--eea8f6e-external
    user: garden-kyma--eea8f6e-external
users:
- name: garden-kyma--eea8f6e-external
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://kyma.accounts.ondemand.com"
      - "--oidc-client-id=12b13a26-d993-4d0c-aa08-5f5852bbdff6"
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      command: kubectl-oidc_login
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
