

server:
  port: ${PORT:8080}

site:
  domain:
    url: https://shop-service-fluent-eland-nk.cfapps.us10-001.hana.ondemand.com


database:
  host: postgres-87554e97-f1e5-4f08-aec0-954abd5f50da.cqryblsdrbcs.us-east-1.rds.amazonaws.com
  port: 6272
  name: AqRRRxPflrIN
  user: cc741b6af4f1
  pass: 5e98153469eb79dc1e4ce24da4b6b1ef

cache:
  url: rediss://:YSZXOIhfKtZihnafJtARQjcsGdAmkwCd@master.rg-35963d75-fac3-4481-911b-10534995bde3.9u04ff.use1.cache.amazonaws.com:1544
  host: master.rg-35963d75-fac3-4481-911b-10534995bde3.9u04ff.use1.cache.amazonaws.com
  port: 1544
  password: YSZXOIhfKtZihnafJtARQjcsGdAmkwCd
spring:
  data:
    redis:
      url: ${cache.url}
      ssl:
        enabled: true
