spring:
  mail:
    properties:
      mail:
        debug: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  sql:
    init:
      mode: never

site:
  domain:
    url: http://127.0.0.1:${server.port}

database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

cache:
  host: ${CACHE_HOST}
  port: ${CACHE_PORT}
  password: ${CACHE_PASSWORD}



cookie:
  secure: false