

server:
  port: ${PORT:8080}

site:
  domain:
    url: https://shop-service-fluent-eland-nk.cfapps.us10-001.hana.ondemand.com


database:
  host: ${DATABASE_HOST}
  port: ${DATABASE_PORT}
  name: ${DATABASE_NAME}
  user: ${DATABASE_USER}
  pass: ${DATABASE_PASS}

cache:
  url: ${CACHE_URL}
  host: ${CACHE_HOST}
  port: ${CACHE_PORT}
  password: ${CACHE_PASSWORD}
spring:
  data:
    redis:
      url: ${cache.url}
      ssl:
        enabled: true
