spring:
  mail:
    properties:
      mail:
        debug: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
  sql:
    init:
      mode: always

site:
  domain:
    url: http://127.0.0.1:${server.port}

database:
  host: localhost
  port: 5430
  name: leverx
  user: EGOR_BONDARENKO
  pass: pass


cookie:
  secure: false