version: '3.8'

services:
  postgres-leverX:
    image: postgres:16
    environment:
      - POSTGRES_USER=EGOR_BONDARENKO
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=leverx
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-leverX:
    image: "redis:alpine"
    command: redis-server --requirepass DxnPvBthsWCKTFGR
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
# TODO
#  leverx-app:
#    build:
#      context: ../
#      dockerfile: Dockerfile
#    ports:
#      - "80:80"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - postgres-leverX
#      - redis-leverX
#
volumes:
  postgres_data:
    driver: local
