

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=EGOR_BONDARENKO
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=leverx
    ports:
      - "5430:5432"


  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --requirepass DxnPvBthsWCKTFGR
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always


volumes:
  postgres_data:
    driver: local