

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=EGOR_BONDARENKO
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=leverx
    ports:
      - "5430:5432"


volumes:
  postgres_data:
    driver: local