apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: shop-service-namespace
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
