apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop-service-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ebndnrk/leverx-final-project:latest
          ports:
            - containerPort: 8071
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
