apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-leverx
  namespace: shop-service-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-leverX
  template:
    metadata:
      labels:
        app: redis-leverX
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server", "--requirepass", "$(CACHE_PASSWORD)"]
          envFrom:
            - secretRef:
                name: backend-secrets
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-leverx
  namespace: shop-service-namespace
spec:
  ports:
    - port: 6379
  selector:
    app: redis-leverX
