create table if not exists public.comment_author
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint comment_author_version_check
    check (version > 0)
    constraint comment_author_version_check1
    check (version >= 1),
    identifier   varchar(255)
    );

comment on column comment_author.id is 'Первичный ключ';

comment on column comment_author.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment_author.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment_author.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';