create table if not exists public.rating
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint rating_version_check
            check (version > 0)
        constraint rating_version_check1
            check (version >= 1),
    mark         smallint                               not null
    constraint rating_mark_check
    check (mark between 0 and 10),
    author_id    bigint
        constraint fk32o6146e5toouucyy9hhfdyrm
            references anonymous_user,
    seller_id    bigint
        constraint fkbjr9gvo8qitfc25pnwqriwkrc
            references profile
);

comment on column rating.id is 'Identifier';

comment on column rating.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column rating.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column rating.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column rating.mark is 'number from 0 to 10';

comment on column rating.author_id is 'anonyomus user made it';

comment on column rating.seller_id is 'seller wich was rated by anonymous user';
