create table if not exists public.seller_from_comment
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint seller_from_comment_version_check
    check (version > 0)
    constraint seller_from_comment_version_check1
    check (version >= 1),
    email        varchar(50),
    firstname    varchar(50),
    lastname     varchar(50),
    username     varchar(50),
    profile_id   bigint
    constraint ukhmuiar9iw50btxtl1liu25o9d
    unique
    constraint fk3vygaocci8cu7riwvcf92xtrl
    references profile
    );

comment on column seller_from_comment.id is 'Identifier';

comment on column seller_from_comment.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column seller_from_comment.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column seller_from_comment.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column seller_from_comment.email is 'The email address of the seller. Must be between 4 and 50 characters.';

comment on column seller_from_comment.firstname is 'The first name of the seller. Must be between 4 and 50 characters.';

comment on column seller_from_comment.lastname is 'The last name of the seller. Must be between 4 and 50 characters.';

comment on column seller_from_comment.username is 'The username of the seller. Must be between 4 and 50 characters.';

comment on column seller_from_comment.profile_id is 'The profile associated with the seller. This field is linked to the Profile entity.';