create table IF NOT EXISTS public.game_object
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint game_object_version_check
    check (version > 0)
    constraint game_object_version_check1
    check (version >= 1),
    text         text,
    title        varchar(255),
    seller_id    bigint
    constraint fkdkt9le3fsqvwymg4v1dgaau54
    references profile
    );

comment on column game_object.id is 'Первичный ключ';

comment on column game_object.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column game_object.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column game_object.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';