create table if not exists public.seller_from_comment
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint seller_from_comment_version_check
            check (version > 0)
        constraint seller_from_comment_version_check1
            check (version >= 1),
    email        varchar(50),
    firstname    varchar(50),
    lastname     varchar(50),
    username     varchar(50),
    profile_id   bigint
        constraint ukhmuiar9iw50btxtl1liu25o9d
            unique
        constraint fk3vygaocci8cu7riwvcf92xtrl
            references profile
);

comment on column seller_from_comment.id is 'Первичный ключ';

comment on column seller_from_comment.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column seller_from_comment.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column seller_from_comment.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';
