create table IF NOT EXISTS game_object
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint game_object_version_check
            check (version > 0)
        constraint game_object_version_check1
            check (version >= 1),
    text         text,
    title        varchar(255),
    user_id      bigint
        constraint fk163y71tw5rb3d6aosixh9naua
            references app_user
);