create table if not exists public.comment
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint comment_version_check
    check (version > 0)
    constraint comment_version_check1
    check (version >= 1),
    approved     boolean,
    message      varchar(255),
    author_id    bigint
    constraint fko83ffw2442neg76w929a2arc3
    references anonymous_user,
    seller_id    bigint
    constraint fk8r5o2nxa75xyrbnu5jx1nvhy
    references profile
    );

comment on table comment is 'List of comments made by the user.';

comment on column comment.id is 'Identifier';

comment on column comment.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column comment.approved is 'A flag indicating whether the comment has been approved by an admin. Default is false.';

comment on column comment.message is 'The message content of the comment. This field is required and cannot be null.';

comment on column comment.author_id is 'The anonymous user who authored the comment. This field is optional.';

comment on column comment.seller_id is 'The seller (profile) to whom the comment is addressed. This field is required and cannot be null.';