create table if not exists public.rating
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint rating_version_check
            check (version > 0)
        constraint rating_version_check1
            check (version >= 1),
    mark         smallint                               not null
    constraint rating_mark_check
    check (mark between 0 and 10),
    author_id    bigint
        constraint fk32o6146e5toouucyy9hhfdyrm
            references anonymous_user,
    seller_id    bigint
        constraint fkbjr9gvo8qitfc25pnwqriwkrc
            references profile
);

comment on column rating.id is 'Первичный ключ';

comment on column rating.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column rating.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column rating.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';
