create table if not exists public.comment
(
    id           bigint generated by default as identity
    primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
    constraint comment_version_check
    check (version > 0)
    constraint comment_version_check1
    check (version >= 1),
    approved     boolean,
    message      varchar(255),
    author_id    bigint
    constraint fk5qwvc51t0ecgi251261ku4l8b
    references comment_author,
    seller_id    bigint
    constraint fk8r5o2nxa75xyrbnu5jx1nvhy
    references profile
    );

comment on column comment.id is 'Первичный ключ';

comment on column comment.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column comment.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';