create table if not exists public.profile
(
    id                    bigint generated by default as identity
    primary key,
    created_dttm          timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at            timestamp(6) default CURRENT_TIMESTAMP not null,
    version               bigint       default 1                 not null
    constraint profile_version_check
    check (version > 0)
    constraint profile_version_check1
    check (version >= 1),
    email                 varchar(50),
    firstname             varchar(50),
    is_confirmed_by_admin boolean                                not null,
    lastname              varchar(50),
    rating                smallint,
    constraint profile_rating_check
    check (rating between 0 and 10),
    username              varchar(50)
    constraint uk5em4hwqp4woqsf49dru7fjo80
    unique
    );

comment on column profile.id is 'Identifier';

comment on column profile.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column profile.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column profile.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column profile.is_confirmed_by_admin is 'Flag indicating whether the profile is confirmed by an admin.';

comment on column profile.username is 'Unique username. Must be between 4 and 50 characters.';