create table if not exists public.app_user
(
    id                 bigint generated by default as identity
    primary key,
    created_dttm       timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at         timestamp(6) default CURRENT_TIMESTAMP not null,
    version            bigint       default 1                 not null
    constraint app_user_version_check
    check (version > 0)
    constraint app_user_version_check1
    check (version >= 1),
    email              varchar(50)                            not null,
    is_email_confirmed boolean                                not null,
    password           varchar(100)                           not null,
    role               varchar(255)                           not null
    constraint app_user_role_check
    check ((role)::text = ANY
((ARRAY ['ROLE_SELLER'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    username           varchar(50)                            not null
    constraint uk3k4cplvh82srueuttfkwnylq0
    unique,
    profile_id         bigint
    constraint uknv8hg42pwanrqg8k89um582st
    unique
    constraint fk4k8ioximnm5upkt9s068b0g3h
    references profile
    );

comment on column app_user.id is 'Identifier';

comment on column app_user.created_dttm is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column app_user.updated_at is 'Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column app_user.version is 'large range number from -9223372036854775808 to +9223372036854775807';

comment on column app_user.email is 'The email address of the user. Must be a valid email and between 4 and 50 characters.';

comment on column app_user.password is 'The password of the user. Must be between 4 and 100 characters. This field is ignored in JSON serialization.';

comment on column app_user.role is 'The role of the user. This field is ignored in JSON serialization.';

comment on column app_user.username is 'The username of the user. Must be unique and between 4 and 50 characters.';

comment on column app_user.profile_id is 'The profile associated with the user. This field is linked to the Profile entity.';
