create table if not exists public.profile
(
    id                    bigint generated by default as identity
        primary key,
    created_dttm          timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at            timestamp(6) default CURRENT_TIMESTAMP not null,
    version               bigint       default 1                 not null
        constraint profile_version_check
            check (version > 0)
        constraint profile_version_check1
            check (version >= 1),
    email                 varchar(50),
    firstname             varchar(50),
    is_confirmed_by_admin boolean                                not null,
    lastname              varchar(50),
    username              varchar(50)
        constraint uk5em4hwqp4woqsf49dru7fjo80
            unique
);

comment on column profile.id is 'Первичный ключ';

comment on column profile.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column profile.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column profile.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';
