create table if not exists public.anonymous_user
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint anonymous_user_version_check
            check (version > 0)
        constraint anonymous_user_version_check1
            check (version >= 1),
    anonymous_id varchar(255)                           not null
        constraint ukdmi1sbwjp79g1rik08xkn7vsp
            unique
);

comment on column anonymous_user.id is 'Первичный ключ';

comment on column anonymous_user.created_dttm is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column anonymous_user.updated_at is 'В формате ISO 8601: YYYY-MM-DD hh:mm:ss.000000';

comment on column anonymous_user.version is 'Целое число с большим диапазоном от -9223372036854775808 до +9223372036854775807';