create table if not exists public.app_user
(
    id           bigint generated by default as identity
        primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at   timestamp(6) default CURRENT_TIMESTAMP not null,
    version      bigint       default 1                 not null
        constraint app_user_version_check
            check (version > 0)
        constraint app_user_version_check1
            check (version >= 1),
    email        varchar(50)                            not null,
    firstname    varchar(50)                            not null,
    lastname     varchar(50)                            not null,
    password     varchar(100)                           not null,
    role         varchar(255)                           not null
        constraint app_user_role_check
            check ((role)::text = ANY
        ((ARRAY ['ROLE_SELLER'::character varying, 'ROLE_ADMIN'::character varying])::text[])),
    username     varchar(50)                            not null
        constraint uk3k4cplvh82srueuttfkwnylq0
            unique,

    is_email_confirmed boolean default FALSE not null,
    is_confirmed_by_admin boolean default FALSE not null
);