name: CI/CD Pipeline

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      - name: Build Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build -t ebndnrk/docker-leverx-backend:${IMAGE_TAG} .
          docker tag ebndnrk/docker-leverx-backend:${IMAGE_TAG} ebndnrk/docker-leverx-backend:latest

      
      - name: Push Docker image
        run: |
          docker push ebndnrk/docker-leverx-backend:${IMAGE_TAG}
          docker push ebndnrk/docker-leverx-backend:latest

      
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

     
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/backend backend=ebndnrk/docker-leverx-backend:${IMAGE_TAG} -n shop-service-namespace
          kubectl rollout status deployment/backend -n shop-service-namespace
